Repository rogeliosamuel621/Thrillo, pull requests merged in 2021-01, with the labels that each got.

#9 feat(middlewares): :sparkles: Add error handler middleware
  server/src/app.js
  server/src/middleware/errorHandler.js
  server/src/middleware/index.js
Labels: enhancement

#8 feat(models): :sparkles: Add user models
  server/src/models/User.js
Labels: enhancement

#10 Modelos todos cards
  server/src/models/Cards.js
  server/src/models/Todo.js
Labels: enhancement

#11 Fix Tests problems
  server/.eslintrc
  server/__test__/utils/dbHandler.js
  server/src/app.js
  server/yarn.lock
Labels: bug

#12 refactor(models): :recycle: rename models
  server/src/models/List.js
  server/src/models/Task.js
  server/src/models/Todo.js
Labels: help wanted

#13 Feature/models
  server/src/models/Board.js
  server/src/models/Column.js
  server/src/models/List.js
  server/src/models/Task.js
  server/src/models/User.js
Labels: enhancement

#14 Feature/nav register
  client/src/App.jsx
  client/src/components/atoms/.gitkeep
  client/src/components/containers/.gitkeep
  client/src/components/molecules/Nav.jsx
  client/src/components/molecules/index.js
  client/src/components/pages/Register.jsx
  client/src/components/pages/index.js
  client/src/styles/app.css
  client/src/styles/molecules/nav.css
Labels: enhancement

#15 Feature/register
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/auth.controllers.js
  server/src/controllers/index.js
  server/src/routes/auth.routes.js
  server/src/routes/index.js
  server/src/validators/auth.validators.js
Labels: enhancement

#16 feat(Style): :sparkles: Added css variable file
  client/src/index.jsx
  client/src/styles/app.css
  client/src/styles/vars.css
Labels: enhancement

#17 feat(Page): :sparkles: Added page board
  client/src/App.jsx
  client/src/components/molecules/BoardCard.jsx
  client/src/components/molecules/index.js
  client/src/components/pages/Board.jsx
  client/src/components/pages/index.js
  client/src/index.jsx
  client/src/styles/pages/board.css
Labels: enhancement

#20 Improvement/styles page board
  client/src/styles/pages/board.css
Labels: enhancement

#22 Feature/styles
  client/src/assets/img/add.svg
  client/src/assets/mocs.js
  client/src/components/molecules/BoardCard.jsx
  client/src/components/pages/Board.jsx
  client/src/styles/molecules/boardCard.css
  client/src/styles/pages/board.css
Labels: enhancement

#19 Feat/improve structure
  server/.eslintrc
  server/package.json
  server/src/app.js
  server/src/controllers/auth.controllers.js
  server/src/controllers/index.js
  server/src/middleware/errorHandler.js
  server/src/middleware/index.js
  server/src/routes/auth.routes.js
  server/src/routes/index.js
  server/src/utils/handleError.js
  server/yarn.lock
Labels: enhancement

#23 refactor(containerRouter): :hammer: Updated code
  client/src/routes/ContainerRouter.jsx
Labels: enhancement

#24 Feature/register
  client/src/App.jsx
  client/src/components/atoms/Input.jsx
  client/src/components/atoms/index.js
  client/src/components/containers/RegisterForm.jsx
  client/src/components/containers/index.js
  client/src/components/pages/Board.jsx
  client/src/components/pages/Login.jsx
  client/src/components/pages/Register.jsx
  client/src/components/pages/index.js
  client/src/index.jsx
  client/src/routes/routes.js
  client/src/styles/atoms/input.css
  client/src/styles/containers/registerForm.css
Labels: enhancement

#26 fix - register
  server/src/app.js
  server/src/controllers/auth.controllers.js
  server/src/controllers/index.js
  server/src/controllers/user.controller.js
  server/src/middleware/errorHandler.js
  server/src/middleware/index.js
  server/src/middlewares/handleBody.js
  server/src/middlewares/handleError.js
  server/src/middlewares/index.js
  server/src/routes/auth.routes.js
  server/src/routes/index.js
  server/src/routes/users.routes.js
  server/src/utils/errorHandler.js
  server/src/validators/auth.validators.js
Labels: enhancement

#27 feat(Containers): :sparkles: Add login form
  client/src/components/containers/LoginForm.jsx
  client/src/components/containers/index.js
  client/src/components/pages/Login.jsx
  client/src/styles/containers/registerForm.css
Labels: enhancement

#28 Feature/page board
  client/src/assets/img/addBlue.svg
  client/src/assets/img/point.svg
  client/src/components/containers/Todo.jsx
  client/src/components/containers/index.js
  client/src/components/pages/Board.jsx
  client/src/components/pages/Boards.jsx
  client/src/components/pages/index.js
  client/src/routes/routes.js
  client/src/styles/containers/todo.css
  client/src/styles/pages/board.css
  client/src/styles/pages/boards.css
  client/src/utils/fakeApi.js
Labels: enhancement

#29 Feature/page board
  client/src/assets/img/search.svg
  client/src/components/atoms/Input.jsx
  client/src/components/molecules/InviteBoardCard.jsx
  client/src/components/molecules/index.js
  client/src/components/pages/Board.jsx
  client/src/styles/molecules/inviteBoardCard.css
  client/src/styles/pages/board.css
  client/src/utils/fakeApi.js
Labels: enhancement

#31 Feature/page about
  client/src/components/atoms/CardTask.jsx
  client/src/components/atoms/index.js
  client/src/components/containers/Column.jsx
  client/src/components/containers/Todo.jsx
  client/src/components/containers/index.js
  client/src/components/pages/About.jsx
  client/src/components/pages/index.js
  client/src/routes/routes.js
  client/src/styles/atoms/cardTask.css
  client/src/styles/containers/column.css
  client/src/styles/containers/todo.css
  client/src/styles/pages/about.css
Labels: enhancement

#33 Client/authentication
  client/.env.example
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/components/containers/RegisterForm.jsx
  client/src/utils/axios.js
  client/webpack.config.js
  server/package-lock.json
  server/package.json
  server/src/app.js
Labels: enhancement

#34 Improve/cient auth
  client/src/components/containers/RegisterForm.jsx
Labels: enhancement
